version: '3.8'
services:
  cache:
    image: redis:7.0.5-alpine
    restart: unless-stopped
    ports:
      - '8075:8075'
    command: redis-server /home/redis/conf/redis.conf
    volumes:
      - cache:/data
      - ./redis-conf:/home/redis/conf
    deploy:
      resources:
        limits:
          memory: 2G
volumes:
  cache:
    driver: local