name: Publish Jupyter3_11 Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Set datetime
      id: datetime
      run: echo "::set-output name=datetime::$(date +%s)"
        
    - name: Checkout files
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./docker/analytics/jupyter3_11
        push: true
        tags: ghcr.io/jeremiah-carlson/dev-tools/jupyter3_11:latest
