name: Publish Jupyter3_11 Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set datetime
      id: datetime
      run: echo "::set-output name=datetime::$(date +%s)"
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ./docker/analytics/jupyter3_11
      run: docker build -t ghcr.io/jeremiah-carlson/jupyter3_11:${{ steps.datetime.outputs.datetime }} -f Dockerfile

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to ghcr.io
      run: docker push ghcr.io/jeremiah-carlson/jupyter3_11:${{ steps.datetime.outputs.datetime }}
