name: Publish Jupyter3_11 Image

on:
  workflow_dispatch:

env:
  DATE_TIME: $(date +%s)

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Change to workdir
      run: cd docker/analytics/jupyter3_11/
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/jeremiah-carlson/jupyter3_11:$DATE_TIME

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to ghcr.io
      run: docker push ghcr.io/jeremiah-carlson/jupyter3_11:$DATE_TIME
